### ISSUE TITLE
Clear journals, and other temporary files, after work during docker build

### ISSUE THREAD

**Issue by daimor** [intersystems-community/iris-community-edition#12]
Size of final docker image is important, but not everything necessary to have in the final image. 
InterSystems [recommends](https://irisdocs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=ADOCK_iris_creating) to clear journals during the docker build. 
And it would be nice If InterSystems will add some option to `iris stop` command to clear it automatically or will clear it automatically, when seeing that it works in `docker build` if possible.

**Comment by evshvarov** [comment]
Fixed in the following release
