### ISSUE TITLE
Set password from variables/secrets instead of file

### ISSUE THREAD

**Issue by daimor** [intersystems-community/iris-community-edition#9]
Using password file, for changing password, was not a good idea. Very difficult to use, and does not help with security. 
Default password, which should be changed after the first use, very bad idea. It means it can be changed by any who will be first, and you will lose control.
So, we need a way to initialize the password, but in a more secure way without default one.

**Comment by evshvarov** [comment]
Fixed in the following release

**Comment by zrml** [comment]
Also is worth noting we are looking at reviewing the whole credential area. There are issues with all present approaches. Even supporting secrets (which I think we should do) there is the problem that there isn't a standard out there on it... it's delicate and at the same time important. Thanks for the feedback.
